### ISSUE TITLE
Unsupported kwargs = [:forecast_resolution]

### ISSUE THREAD

**Issue by thamer-ee** [NREL-Sienna/PowerSystems.jl#1002]
Frist time using PowerSystem.jl and working in Julia language for energy system modelling. 

I was following the below YouTube video for the Unit Commitment - Energy System Modeling and analysis Tutorial with Julia

[JuliaCon 2020 | Crash Course in Energy Systems Modeling & Analysis with Julia" by Dheepak Krishnamurthy 
](https://www.youtube.com/watch?v=kQNOG4tGJdg&t=91s&ab_channel=TheJuliaProgrammingLanguage)

Everything was smooth until I encountered the following error: 
`"ERROR: Unsupported kwargs = [:forecast_resolution]"
`

Not sure why I am receiving this error message since the same line of code is used as shown in the tutorial: 
`"julia> system = System(tabledata; forecast_resolution = Dates.Hour(1))"
`

Could anyone quickly help with what might be causing this issue? 
I was also wondering if the code related to the YouTube-Unit commitment tutorial is available on GitHub, as I couldn't find it.

Many thanks

**Comment by jd-lara** [comment]
@thamer-ee the forecast_resolution kwarg was removed. Looks like the tutorial might be outdated. Which timestamp in the video are you looking into? So we can provide info for the new API.

**Comment by thamer-ee** [comment]
Thanks, and the timestamp should around 3:00: The  line code` system = System(tabledata; forecast_resolution = Dates.Hour(1))` successfully running. 

The below code (_same in the YouTube Tutorial_) should reproduce the error [Unsupported kwargs = [:forecast_resolution]
```
using PowerSystems
using PowerSimulations
using PowerModels
using PowerGraphics
using Xpress
using Logging
using Dates
rts_dir      = expanduser("**Path to the file>>**\\RTS-GMLC");
rts_data_dir = joinpath(rts_dir,"RTS_Data");
rts_src_dir  = joinpath(rts_data_dir,"SourceData");
rts_fmt_dir  = joinpath(rts_data_dir,"FormattedData","SIIP");
tabledata    = PowerSystems.PowerSystemTableData(
                rts_src_dir,
                100.0,
                joinpath(rts_fmt_dir,"user_descriptors.yaml"),
                timeseries_metadata_file = joinpath(
                    rts_fmt_dir, "timeseries_pointers.json"
                ),
                generator_mapping_file = joinpath(
                    rts_fmt_dir, "generator_mapping.yaml"
                ),
)
system = System(tabledata; forecast_resolution = Dates.Hour(1))
```

**Comment by jd-lara** [comment]
@thamer-ee unfortunately the video corresponds to an earlier version of PowerSystems.jl I will close the issue since the behavior is expected.
