### ISSUE TITLE
Give error or warning when assigning services to a device from another system

### ISSUE THREAD

**Issue by rodrigomha** [NREL-Sienna/PowerSystems.jl#1016]
Currently, when assigning a services to a device from another system it does not give any warning or error.

```
sys1 = build_system("sys1")
sys2 = build_system("sys2")
device2 = first(get_component(ThermalStandard, sys2))
for service1 in get_components(Reserve, sys1)
    add_service!(device2, service1, sys2)
end
```

**Comment by daniel-thom** [comment]
I expect that your specific service does not support time series. Is that correct? We should throw an error if you do this on any component that defines the method `get_time_series_container`. Obviously, that is insufficient. At some point we started storing a reference to the system’s unit setting inside each component. We could use that to tell that a user is trying to assign the component to a second system.
