### ISSUE TITLE
Inverter Output Current Limit implementation 

### ISSUE THREAD

**Issue by jd-lara** [NREL-Sienna/PowerSystems.jl#1054]
- [x] rename the limiter to output current limiter 
- [x] Review fields https://nrel-sienna.github.io/PowerSystems.jl/stable/model_library/generated_InverterLmiter/ 
- [x] Change implementation of the magnitudes for instantaneous limiter to allow for separate i_d and i_q.

**Comment by HaleyRoss** [comment]
Good news, went to review the fields and the instantaneous limiter already allows for setting i_d and i_q independently. So task #3 is complete.
