### ISSUE TITLE
Support for different resolution time series

### ISSUE THREAD

**Issue by jd-lara** [NREL-Sienna/PowerSystems.jl#1068]
For a long time we avoided having time series with different resolutions e.g. some time series with Hourly Data and others with 5 min data. 

For new applications with asset optimization and expansion problems this is getting to be needed. Users (including myself) are using EXT a lot for this application.

**Comment by jd-lara** [comment]
just different resolutions. Mixed resolutions is a different problem

**Comment by jd-lara** [comment]
After a conversation with @daniel-thom we can implement this in PowerSystems v4 and change the checks. We would need to add interfaces to do the following. 

1. Set the default interval for the system
2. Read the existing intervals in the system
3. Check that the intervals are "aligned" I.e, not support 1 hour and 7 minute intervals for the same system

**Comment by daniel-thom** [comment]
> After a conversation with @daniel-thom we can implement this in PowerSystems v4 and change the checks. We would need to add interfaces to do the following.
> 
>     1. Set the default interval for the system
> 
>     2. Read the existing intervals in the system
> 
>     3. Check that the intervals are "aligned" I.e, not support 1 hour and 7 minute intervals for the same system

To be clear, we don't currently have an explicit `set interval` command and still won't with the new implementation. This happens implicitly by adding the first forecast to the system.

We currently require that all forecasts have the same interval, horizon, and window count. Above you are saying that intervals must still be the same regardless of resolution. Shall I add a rule that says horizon and window count must be the same for all forecasts with same resolution?

**Comment by daniel-thom** [comment]
Suppose a system has SingleTimeSeries with different resolutions. How is `transform_single_time_series!` impacted? Does it need a `resolution` parameter, required or optional?
