### ISSUE TITLE
PSY Remaining TODOs for Second Cost Refactor

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerSystems.jl#1092]
This is a list of TODOs that remain unfinished from https://github.com/NREL-Sienna/PowerSystems.jl/pull/1071, they should all be addressed before PSY 4 is released.

- [x] Make other fields of `MarketBidCost` time series, see https://github.com/NREL-Sienna/PowerSystems.jl/pull/1071#discussion_r1579880930
- [x] #1123
- [x] Nail down what is part of the public interface (e.g., just the cost aliases or ValueCurves?)
- [x] Do this to support 3 -> 4 system conversions (EDIT: we are no longer committing to implementing all of these): https://github.com/NREL-Sienna/PowerSystems.jl/blob/234936ef5e06c47388d560511ec6c817f4f30864/src/data_format_conversions.jl#L107
- [x] Minor TODO(?): https://github.com/NREL-Sienna/PowerSystems.jl/blob/234936ef5e06c47388d560511ec6c817f4f30864/test/test_constructors.jl#L24
- [x] Minor TODO: https://github.com/NREL-Sienna/PowerSystems.jl/blob/234936ef5e06c47388d560511ec6c817f4f30864/src/PowerSystems.jl#L553
- [x] Fill in TODOs in https://github.com/NREL-Sienna/PowerSystems.jl/blob/234936ef5e06c47388d560511ec6c817f4f30864/docs/src/modeler_guide/cost_functions.md
- [x] Address https://github.com/NREL-Sienna/PowerSystems.jl/issues/1048
- [x] Already covered by other items, but https://github.com/NREL-Sienna/PowerSystems.jl/blob/234936ef5e06c47388d560511ec6c817f4f30864/src/models/cost_functions/cost_aliases.jl#L84
- [x] Finalize decision on cost-related time series getters and setters: currently the setter takes a time series but the getter returns a time array, this is convenient but violates a certain symmetry. See https://github.com/NREL-Sienna/PowerSystems.jl/pull/1101#issuecomment-2101373414

**Comment by jd-lara** [comment]
On the `get_points`, it isn't too much of a problem since the geographic info uses GeoJSON blobs.

**Comment by GabrielKS** [comment]
wrt "Nail down naming of everything," would someone with a power systems background like to review my naming?

**Comment by jd-lara** [comment]
@GabrielKS can you update the list and close if this is pretty much ready please?
