### ISSUE TITLE
`System` constructor keyword argument `load_zone_formatter` is ignored

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerSystems.jl#1160]
There is a kwarg `load_zone_formatter` listed as one of the supported `SYSTEM_KWARGS`:
https://github.com/NREL-Sienna/PowerSystems.jl/blob/71b9bf406ef7001eb5d6b56cc780b73093c9eb54/src/base.jl#L13
but, unlike all the other `SYSTEM_KWARGS`, nothing is ever done with it. This is the only reference to it in the codebase. I'm currently in a situation where I need to remap the names of load zones, so it would be nice to support this behavior as we do for buses, generators, branches, etc.

**Comment by GabrielKS** [comment]
`good first issue` because if all we need is a name formatter I think it could be implemented pretty similarly to the existing ones

**Comment by rodrigomha** [comment]
What do you need to do here? The main problem is that powerworld does not create a zone dictionary. The load zones are created manually based on the information in the `bus` dictionary in `bus["zone"]` key. Would be tricky to pass a function is that we don't have access at the moment of creation of any additional data `x` that we can do something.

**Comment by GabrielKS** [comment]
@rodrigomha my use case is [here](https://github.com/NREL-Sienna/PowerFlows.jl/blob/67c176e0f9d9d59dbdaa7c6fb44e34c9829c958b/src/psse_export.jl#L1011L1018) — I am creating a `System` from a PSS/E .raw file and adjusting a bunch of names based on a JSON that gets written alongside the .raw by the  new Sienna PSS/E exporter. All I need is the ability to pass in a mapping from what Sienna thinks the name should be to what I actually want the name to be and have that be evaluated.
