### ISSUE TITLE
Docs: add how-to on building a system from scratch

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-Sienna/PowerSystems.jl#1198]
We have how-tos on parsing systems and loading from case builder, but it would be useful to have one that shows you how to build a system from individual components from scratch.

- suggested by @sourabhdalvi

**Comment by kdayday** [comment]
@claytonpbarrows @sourabhdalvi Please see the [Create and Explore a Power System](https://nrel-sienna.github.io/PowerSystems.jl/stable/tutorials/creating_system/) tutorial and let me know if that matches what you're looking for

**Comment by kdayday** [comment]
Will be addressed by Anna's how to
