### ISSUE TITLE
Move `with_units` here from PowerFlows.jl

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerSystems.jl#1229]
In a recent pull request to PowerFlows.jl, I've prototyped this function [`with_units`](https://github.com/NREL-Sienna/PowerFlows.jl/blob/465e92fcf921c460f1bd9e0c042c2cc335897c2f/src/psse_export.jl#L47) that can be combined with the Julia `do` block to perform some action with a `System` under a particular units setting without permanently changing the units setting:

```julia
with_units(sys, PSY.UnitSystem.SYSTEM_BASE) do
  # things in this block will evaluate as if the System's unit system was SYSTEM_BASE no matter what it was before
end
# the System's unit system is back to normal
```

I think it should be moved to PSY and exported. Also

- A less heavy-handed approach to suppressing the logging should probably be taken
- Tests need to be written

Adding this as an issue here in case someone wants to take it on to learn about writing tests, etc. — otherwise I'll do it myself later this week.

**Comment by jd-lara** [comment]
We should add this to the power flow project
