### ISSUE TITLE
Document how custom structs should use type of system

### ISSUE THREAD

**Issue by josephmckinsey** [NREL-Sienna/PowerSystems.jl#904]
Getters and setters for components assume that data is stored in a struct as p.u., and then they are converted to the system settings.

- `docs/src/model_developer_guide/adding_custom_types.md` should mention that you should implement unit conversion.
- `docs/src/modeler_guide/system.md` should mention that internal units are `DEVICE_BASE`.

**Comment by jd-lara** [comment]
@josephmckinsey, we have a plan to address some of this by automatic parts of the process. I think that rather than just documenting, we need to simplify the process for the users.

**Comment by jd-lara** [comment]
This is addressed In https://nrel-sienna.github.io/PowerSystems.jl/stable/modeler_guide/system/#per_unit
