### ISSUE TITLE
add time series checker function

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-Sienna/PowerSystems.jl#911]
Add a function that allows users to check the time series in a system for:
- valid `scaling_factor_multipliers`
- values in range 0 - 1.0
- constant resolution and length
- consistency across device types (all active RE gens should have a time series...) (nice to have) 
- anything else?

**Comment by jd-lara** [comment]
Implemented post- parsing not as part of the parsing

**Comment by jd-lara** [comment]
add helper function to the time series. Similar to `show_components` but for time series.

**Comment by jd-lara** [comment]
closing since this is stale and most of this list is implemented by default.
