### ISSUE TITLE
Document addition of time series data with transformed time series. 

### ISSUE THREAD

**Issue by ktehranchi** [NREL-Sienna/PowerSystems.jl#935]
I’m attempting to add a new HydroEnergyReservoir with a hydroCommitmentReservoirBudget formulation to the modified-RTS-GMLC-DA system from casebuilder. I intend to use the `hydrobudget` as a daily “MWH” budget that a new `hydroEnergyReserviour` can dispatch each day…. My TS CSV has two columns with 365 values of the daily energy budget. 

The current error- is "InfrastructureSystems.ConflictingInputsError("forecast horizon 1 does not match system horizon 48". Jose has identified the issue is that the static time-series would need to be in the deterministic forecast format to be added to the system because this case-builder system is modified to include forecasts already. 

Apologies for my poor explanation. Code attached.

[hydroSim_2016_@.csv](https://github.com/NREL-SIIP/PowerSystems.jl/files/10180207/hydroSim_2016_%40.csv)
[issue.txt](https://github.com/NREL-SIIP/PowerSystems.jl/files/10180216/issue.txt)

**Comment by jd-lara** [comment]
This issue is related to trying to add data to a system with transformed time series. This is mostly a documentation issue on how to handle these cases

**Comment by jd-lara** [comment]
@kdayday and @daniel-thom can we. confirm this case is covered in the documentation? If yes please close the issue.
