### ISSUE TITLE
Add documentation for updated Cost Functions models

### ISSUE THREAD

**Issue by rodrigomha** [NREL-Sienna/PowerSystems.jl#985]
I think if a VariableCost is of the form `VariableCost([(1.0, 1.0), (2.0, 1.1), (3.0, 1.2)])` the first element of each tuple is the power when the line ends, and the second term is the slope?

**Comment by claytonpbarrows** [comment]
the first term in each tuple is the cost, the second term is the quantity.
We need to document this properly.

**Comment by rodrigomha** [comment]
Updated to do in tandem with #1007

**Comment by GabrielKS** [comment]
@jd-lara Noting for the record that there are inconsistent references on how to interpret `VariableCost((0.0, 14.0))`:

  1. Ascending: [this](https://nrel-sienna.github.io/PowerSimulations.jl/latest/formulation_library/General/#Polynomial-VariableCost) says this is `f(x) = 0.0 x + 14.0 x^2`
  2. Descending: [this](https://github.com/NREL-Sienna/PowerSimulations.jl/blob/v0.27.0/src/devices_models/devices/common/objective_functions.jl#L443L468), [this](https://github.com/NREL-Sienna/PowerSimulations.jl/blob/v0.27.0/src/devices_models/devices/thermal_generation.jl#L122), and [this](https://github.com/NREL-Sienna/PowerSystems.jl/blob/main/src/parsers/power_models_data.jl#L448) (given the input data definition in Table B-4 [here](https://matpower.org/docs/MATPOWER-manual.pdf)) say this is `f(x) = 0.0 x^2 + 14.0 x`

In my ongoing refactor to eliminate `VariableCost` entirely, I will assume existing `VariableCost`s constructed this way should be interpreted as per option 2.
